### ISSUE TITLE
Benötigte Sprache dropdown is empty

### ISSUE THREAD

**Issue by mpavey0** [refugeehackathon/interpreteer-frontend#13]
![image](https://cloud.githubusercontent.com/assets/12401696/11312316/45023968-8fcd-11e5-922d-8b7f2ae183b2.png)

**Comment by dahoo** [comment]
Thanks. The languages were provided by Django, so we need a replacement for that. I added it to the Ember tasks in #4.

**Comment by mpavey0** [comment]
Got it. Great!
